### ISSUE TITLE
Conflicts with sortablejs plugin

### ISSUE THREAD

**Issue by dajaganz** [dwp-forge/tablewidth#2]
When both these plugins are enabled, sortable tags have no effect.  Do we need to explicitly add a tablewidth row?

**Comment by dwp-forge** [comment]
Just did a quick test using Hrun and this seems to work just fine:

``` <sortable>
^Col1^Col3^Col3^
|1|one|25/12/2008|
|2|two|10/12/2008|
</sortable>

<sortable>
|<100% 20em 20em>|
^Col1^Col3^Col3^
|3|one|25/12/2008|
|4|two|10/12/2008|
</sortable>
```

Both tables can be sorted by clicking on the title row.

**Comment by dajaganz** [comment]
Thanks for doing that.  Tried your sample tables and found they work :|  Have not since been able to reproduce my issue though I managed three times before posting this question.  Will close this now. Thanks!
