### ISSUE TITLE
cannot decrease table with below 50%

### ISSUE THREAD

**Issue by asheenlevrai** [dwp-forge/tablewidth#4]
Hello,

I recently installed this plugin (tablewidth) and tried to play around with it in order to manually specify the width of some of my tables and the width of each column inside these tables.

What I noticed is that **I cannot make tables occupy less than 50% of the page width**, no matter what. For instance if I setup a table with 2 columns as:
`|< 100% 20% 80% >|`
(1st value is table width, 2nd value is width of column1 3rd value is width of column2)
Then it works as expected.

However, if I do the following:
`|< 40% 20% 20% >|`
or even (see remark below)
`|< 40% 20% 80% >|`
It doesn't . The width of the table is always 50% of the width of the page even when the 1st value is below 50%.

**Remark**: _After reading the documentation I didn't understand if the 2nd and subsequent values are relative to the 1st value or to the whole page. That is for instance:_
`|< 80% 50% 50% >|`
_Does this make sense or not?_
- _the table is expected to use 80% of the width of the page according to the 1st value_
- _the 1st column is expected to use:_

-> _a) 50% of the width of the page? (the the 3rd value at 50% doesn't really make sense_

-> _b) 40% of the width of the page? (50% of those 80% defined by the first value)_

I don't know if the fact that I cannot shrink tables below a certain point (50%) is an issue with this plugin or with DW. I don't really understand how DW automatically determines what should be the width of tables, columns, etc... I noticed for instance that tables don't always occupy 100% of the width although they do occupy more than the minimal required space based on the data contained in the tables.

Anyway, any help is welcome.
Best,
-a-

PS: I'm using a 30'' monitor. I didn't try smaller displays, yet

**Comment by dwp-forge** [comment]
This is indeed a bug. The current default template sets minimal table width to 50% of the page. This can be overridden by the plugin, so I will release an update.

As for the relative units, there is an example on the [plugin page](https://www.dokuwiki.org/plugin:tablewidth#syntax):

```
|< 50em 20% >|
^ 20%              ^ 80%                          ^
| Specified width  | The rest of the table width  |
```

The table width is 50em, the first column is 20% of that, the second -- the rest of the table width (80%).

**Comment by dwp-forge** [comment]
The fix has been [released](https://www.dokuwiki.org/plugin:tablewidth#section20161013). I also added clarification regarding the relative units to the syntax description section.

**Comment by asheenlevrai** [comment]
Thank you SO much, you're the best!
Now it is crystal clear and works perfectly.
Thumbs up! I appreciate :)
-a-
