### ISSUE TITLE
does not workt with <code>

### ISSUE THREAD

**Issue by zounp** [dwp-forge/tablewidth#5]
I does not work when a <code>Some code</code> tag is used in the table

**Comment by dwp-forge** [comment]
You might need to put some spaces around the `<code>` section to make it work:
```
|< 30% >|
| <code>Test</code> |
```

**Comment by zounp** [comment]
Hello Mykola, Thanks. It works fine now :-) 05.07.2017, 07:34, "Mykola Ostrovskyy" <notifications@github.com>:You might need to put some spaces around the <code> section to make it work:|< 30% >|
| <code>Test</code> |
