### ISSUE TITLE
dokuwiki crash with tablewidth enabled

### ISSUE THREAD

**Issue by mytikfy** [dwp-forge/tablewidth#7]
The following line |< 95% >| (table width setting) crashes and returned an empty page:

versions:
system: arch linux 
php: php 8.0.14-1 (cannot updated because of nextcloud)
dokuwiki 20200729-3

info from httpd logging (apache)
<pre>
[Mon Feb 07 17:12:36.294506 2022] [php:error] [pid 279887] [client 192.168.55.224:42832] 
PHP Fatal error:  Uncaught Error: Call to undefined method Doku_Handler::() in /usr/share/webapps/dokuwiki/inc/Parsing/Lexer/Lexer.php:273
Stack trace:
#0 /usr/share/webapps/dokuwiki/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\\Parsing\\Lexer\\Lexer->invokeHandler('\\n|< 95% >|', 5, 33)
#1 /usr/share/webapps/dokuwiki/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\\Parsing\\Lexer\\Lexer->dispatchTokens('Table', '\\n|< 95% >|', '_', 28, 33)
#2 /usr/share/webapps/dokuwiki/inc/Parsing/Parser.php(109): dokuwiki\\Parsing\\Lexer\\Lexer->parse('\\n| test | tea |...')
#3 /usr/share/webapps/dokuwiki/inc/parserutils.php(216): dokuwiki\\Parsing\\Parser->parse('\\n====== Playgro...')
#4 /usr/share/webapps/dokuwiki/inc/html.php(294): p_get_instructions('====== Playgrou...')
#5 /usr/share/webapps/dokuwiki/inc/Action/Preview.php(25): html_show('====== Playgrou...')
#6 /usr/share/webapps/dokuwiki/inc/template.php(99): dokuwiki\\Action\\Preview->tplContent()
#7 [internal function]: tpl_content_core('preview')
#8 /usr/share/webapps/dokuwiki/inc/Extension/Event.php(129): call_user_func_array('tpl_content_cor...', Array)
#9 /usr/share/webapps/dokuwiki/inc/Extension/Event.php(195): dokuwiki\\Extension\\Event->trigger('tpl_content_cor...', true)
#10 /usr/share/webapps/dokuwiki/inc/template.php(84): dokuwiki\\Extension\\Event::createAndTrigger('TPL_ACT_RENDER', 'preview', 'tpl_content_cor...')
#11 /var/lib/dokuwiki/tpl/dokuwiki/main.php(58): tpl_content()
#12 /usr/share/webapps/dokuwiki/inc/actions.php(27): include('/var/lib/dokuwi...')
#13 /usr/share/webapps/dokuwiki/doku.php(122): act_dispatch()
#14 {main}\n  thrown in /usr/share/webapps/dokuwiki/inc/Parsing/Lexer/Lexer.php on line 273, referer: 
</pre>

**Comment by sromeroi** [comment]
I'm having the same issue with PHP 8.1:

The following code:

```
|< 75% >|
^ Title ^ Date ^  HTML ^ PDF ^
(etc..)
```

Produces:

```
Error: Call to undefined method Doku_Handler::()
An unforeseen error has occured. This is most likely a bug somewhere.
More info has been written to the DokuWiki error log.
```

Manually editing the dokuwiki content to remove `|< 75% >|` or disabling Table Width plugin fixes the issue, so it is due to something that table Plugin does.

**Comment by dwp-forge** [comment]
Fixed in [v.2022-08-09](https://github.com/dwp-forge/tablewidth/releases/tag/v.2022-08-09).

**Comment by sromeroi** [comment]
Working perfectly now, thanks a lot.
